'use strict';
/**
 * 樣本有限的鉤子（只建立機制與初步資料，不做結論；資訊性，不判定）。   node tests/limited_sample_curves.js [--draws 500]
 * 實務接收機（ofdm_ici.js 的 practicalWeights）：R_yy 只用 Ns 個子載波估計（Ns ∈ {4, 8, 12, 24, 48, 96, N}），
 *   S 的選法：連續 Ns 個子載波（'contiguous'）或均勻間隔（'uniform'）；
 *   正則化：'none'（Ns ≥ Nr 時直接求逆，否則偽逆）或 'dl'（γ = γ_rel σn²，這裡 γ_rel = +10 dB）。
 * R_yy 含訊號；對頻 ε̂ 由含雜訊樣本的 CP 法估計；Ĥ 由導頻估計（Ns 只影響 R_yy，不影響 Ĥ）。
 * 設定：N = 1024、Δf = 15 kHz、Nr = 2 與 4、速度 300 與 450 km/h（f_m = v·fc/c，fc = 5 GHz；路徑都卜勒 = f_m × [1, −1, 0.70, 0.20]，假設 A6）、
 *   SNR 20 與 30 dB、到達角每次從 U(−90°, 90°) 隨機抽取（假設 A4）、每格 ≥ 500 次實現、同一個通道與符元用在所有 (Ns, 選法, 正則化) 組合（成對）。
 * 輸出 data/limited_sample_nr2.csv 與 data/limited_sample_nr4.csv：mean 與 SE（dB）。另附「Optimal BF（CP 對頻，解析）」作參考。
 */
const fs = require('fs'), path = require('path');
const O = require('../ofdm_ici.js');
const U = require('./_util.js');
const R = require('./reproduce_gopala_slock.js');

const NS = [4, 8, 12, 24, 48, 96, 1024], SELECT = ['contiguous', 'uniform'], REG = [['none', 0], ['dl', 10]], SPEEDS = [300, 450], SNRS = [20, 30], FC = 5e9, C = 3e8;
const dB = x => 10 * Math.log10(x);

function compute(Nr, draws, seed = R.CFG.seed) {
    const N = R.CFG.N, Ncp = R.CFG.Ncp, rows = [];
    for (const v of SPEEDS) {
        const fm = v / 3.6 * FC / C, scale = fm / 1080;                        // 最大路徑偏移 = f_m
        const acc = {}, ref = SNRS.map(() => []);
        for (let t = 0; t < draws; t++) {
            const rp = O.makeRng(seed + 7919 * t), ra = O.makeRng(seed + 500000 + 7919 * t), rs = O.makeRng(seed + 1000000 + 7919 * t + v);
            const ch = O.paperChannel(R.pickAngles('random', ra), rp, { Nr, N, dopplerScale: scale });
            SNRS.forEach((snr, si) => {
                const sn2 = O.snrToNoise(ch, snr, 1), sym = O.makeSymbol(ch, { rng: rs, sigmaX2: 1, sigmaN2: sn2, Ncp, pilotSpacing: 12 }), eh = O.epsCpEstimate(sym), Y = O.demodulate(sym, eh), sys = O.system(ch, eh, 1, sn2);
                ref[si].push(dB(O.optimal(sys.H, sys.R, Nr, 1).sinr));            // 同一個 ε̂ 下的最佳 SINR（參考）
                for (const sel of SELECT) for (const [reg, gdb] of REG) for (const Ns of NS) {
                    const key = `${si}|${sel}|${reg}|${Ns}`, pw = O.practicalWeights(sym, Y, { Ns, select: sel, reg, gammaRel: Math.pow(10, gdb / 10) });
                    (acc[key] = acc[key] || []).push(dB(O.sinrOfWeights(pw.G, sys.H, sys.R, Nr, 1)));
                }
            });
        }
        SNRS.forEach((snr, si) => {
            rows.push([Nr, v, snr, 'reference', 'optimal at eps_hat', 'N', U.mean(ref[si]).toFixed(4), U.se(ref[si]).toFixed(4), draws]);
            for (const sel of SELECT) for (const [reg, gdb] of REG) for (const Ns of NS) { const a = acc[`${si}|${sel}|${reg}|${Ns}`]; rows.push([Nr, v, snr, sel, reg === 'dl' ? `dl(+${gdb} dB)` : 'none', Ns, U.mean(a).toFixed(4), U.se(a).toFixed(4), draws]); }
        });
    }
    return rows;
}

if (require.main === module) {
    const argv = process.argv.slice(2), draws = argv.includes('--draws') ? +argv[argv.indexOf('--draws') + 1] : 500, root = path.join(__dirname, '..', 'data'), t0 = Date.now();
    for (const Nr of [2, 4]) {
        const rows = compute(Nr, draws), hdr = [`Limited-sample receiver: SINR (dB) versus the number Ns of subcarriers used for R_yy; Nr = ${Nr}`,
            `schema_version 1; generated by tests/limited_sample_curves.js; seed ${R.CFG.seed}; ${draws} realisations per cell (the same channel and symbol for all Ns / selection / regularisation: paired)`,
            `N ${R.CFG.N}, delta_f ${R.CFG.df} Hz, Ncp ${R.CFG.Ncp}, pilot spacing 12, QPSK, R_yy contains the signal; epsilon from the CP method (noisy samples); H_hat from the pilots (all pilots)`,
            `speeds 300 and 450 km/h: f_m = v fc / c with fc = 5 GHz, path Dopplers = f_m x [1, -1, 0.70, 0.20] (assumption A6), relative powers [0, 0, -11, -0.7] dB, random phases, angles U(-90, 90) deg per realisation (A4); SNR 20 and 30 dB (A1)`,
            'select: contiguous = Ns consecutive subcarriers starting at 0, uniform = Ns subcarriers spread evenly; reg: none = direct inverse (pseudo-inverse if Ns < Nr), dl(+10 dB) = diagonal loading gamma = 10 sigma_n^2',
            'row "reference": optimal beamformer at the same epsilon_hat (analytic). Informational only: no conclusion is drawn from these curves yet.'];
        fs.writeFileSync(path.join(root, `limited_sample_nr${Nr}.csv`), hdr.map(l => '# ' + l).join('\n') + '\nNr,v_kmh,snr_db,select,reg,Ns,mean_sinr_db,se_db,n\n' + rows.map(r => r.join(',')).join('\n') + '\n');
        console.log(`Nr = ${Nr}: ${rows.length} rows written (${((Date.now() - t0) / 1000).toFixed(0)} s)`);
    }
}
module.exports = { compute, NS };
