'use strict';
/**
 * 乾淨片的第三版：導頻子載波訓練的協方差估計 + Ledoit–Wolf 收縮（資訊性）。   node tests/map_clean_lw.js [--part k/n] | --merge
 * 與 tests/map_v2.js 的 cell() 同一條計算路徑、同一個種子與 200 次實現（SNR 20 dB，704 格），只把權重改成 pilotResidualWeights(..., { shrink: 'lw' })，
 * 所以 SINR_opt 與 map_v2.csv 相同，L_est_lw = SINR_opt − SINR_LW。輸出 data/map_clean_lw.csv（只有新欄位；舊檔不動）。
 */
const fs = require('fs'), path = require('path');
const O = require('../ofdm_ici.js');
const U = require('./_util.js');
const R = require('./reproduce_gopala_slock.js');
const M = require('./map_v2.js');

const C = 3e8, N = R.CFG.N, Ncp = R.CFG.Ncp, SNR = 20, dB = x => 10 * Math.log10(x), DOPP = [1, -1, 0.70, 0.20], REL = [0, 0, -11, -0.7];
function cellLw(v, fc, df, Nr, draws, seed) {
    const fm = v / 3.6 * fc * 1e9 / C, opt = [], lw = [];
    for (let t = 0; t < draws; t++) {
        const rp = O.makeRng(seed + 7919 * t), ra = O.makeRng(seed + 500000 + 7919 * t), rs = O.makeRng(seed + 1000000 + 7919 * t);
        const ang = R.pickAngles('random', ra), ch = O.makeChannel({ N, Nr, df: df * 1e3, rng: rp, paths: DOPP.map((k, i) => ({ fHz: fm * k, thetaDeg: ang[i], powerDb: REL[i] })) });
        const sn2 = O.snrToNoise(ch, SNR, 1), sym = O.makeSymbol(ch, { rng: rs, sigmaX2: 1, sigmaN2: sn2, Ncp, pilotSpacing: 12 }), eh = O.epsCpEstimate(sym), Y = O.demodulate(sym, eh), s = O.system(ch, eh, 1, sn2);
        opt.push(dB(O.optimal(s.H, s.R, Nr, 1).sinr)); lw.push(dB(O.sinrOfWeights(O.pilotResidualWeights([{ sym, Y }], { shrink: 'lw' }).G, s.H, s.R, Nr, 1)));
    }
    return { Lest: U.mean(opt) - U.mean(lw), se: U.se(opt.map((x, i) => x - lw[i])) };
}
const root = path.join(__dirname, '..', 'data'), argv = process.argv.slice(2);
if (require.main === module) {
    if (argv.includes('--merge')) {
        const rows = []; for (const f of fs.readdirSync(root).filter(f => /^map_clean_lw\.part\d+\.csv$/.test(f)).sort()) rows.push(...fs.readFileSync(path.join(root, f), 'utf8').trim().split('\n').slice(1));
        rows.sort((a, b) => { const x = a.split(','), y = b.split(','); return (+x[3] - +y[3]) || (+x[1] - +y[1]) || (+x[2] - +y[2]) || (+x[0] - +y[0]); });
        fs.writeFileSync(path.join(root, 'map_clean_lw.csv'), '# Third version of the clean-estimator slice: Ledoit-Wolf shrinkage of the pilot-subcarrier covariance, SNR 20 dB, same cells, seed and 200 realisations as data/map_v2.csv; generated by tests/map_clean_lw.js\nv_kmh,fc_GHz,df_kHz,Nr,L_est_lw_db,L_est_lw_se,n\n' + rows.join('\n') + '\n');
        for (const f of fs.readdirSync(root).filter(f => /^map_clean_lw\.part\d+\.csv$/.test(f))) fs.unlinkSync(path.join(root, f)); console.log(rows.length + ' cells merged');
    } else {
        const part = argv.includes('--part') ? argv[argv.indexOf('--part') + 1].split('/').map(Number) : [0, 1], grid = [], rows = [];
        for (const Nr of M.NRS) for (const fc of M.FCS) for (const df of M.DFS) for (const v of M.VS) grid.push([v, fc, df, Nr]);
        grid.forEach((g, gi) => { if (gi % part[1] !== part[0]) return; const r = cellLw(g[0], g[1], g[2], g[3], 200, R.CFG.seed); rows.push([...g, r.Lest.toFixed(3), r.se.toFixed(3), 200].join(',')); });
        fs.writeFileSync(path.join(root, `map_clean_lw.part${part[0]}.csv`), 'v_kmh,fc_GHz,df_kHz,Nr,L_est_lw_db,L_est_lw_se,n\n' + rows.join('\n') + '\n');
    }
}
module.exports = { cellLw };
