'use strict';
/**
 * C3 迷你限制因素地圖 v2（資訊性，不判定，不改 UI）。
 *   node tests/map_v2.js [--draws 200] [--part k/n]     只算第 k 份格點 → data/map_v2.part<k>.csv
 *   node tests/map_v2.js --merge                          合併 → data/map_v2.csv、data/map_v2_critical.csv、docs/diagnostics/map_v2_summary.txt
 * 軸：v ∈ {0, 50, …, 500} km/h；fc ∈ {3.5, 7, 15, 28} GHz；Δf ∈ {15, 30, 60, 120} kHz；Nr ∈ {2, 4, 8, 16}；SNR ∈ {10, 20, 30} dB（SNR 軸為本輪新增，取值是我的選擇）。
 * 其他設定同 tests/map_prototype.js（N = 1024、Ncp = 72、導頻間距 12、4 路徑、都卜勒 f_m × [1, −1, 0.70, 0.20]、隨機到達角與相位、CP 法 ε̂）。
 * 損失（成對，對實現平均）：
 *   L_ICI_net   = 10 log10(Nr SNR / SINR_opt) − 同一個 (Nr, SNR) 在 v = 0 的值（Doppler 造成的部分；下限 0）
 *   L_est       = SINR_opt − SINR_pilot-residual（無加載，m = 1）                 「乾淨」估計器（切片 i）
 *   L_est_naive = SINR_opt − SINR_estimated（含訊號的樣本 R_yy，全部 1024 個子載波）   切片 ii
 * 切片 i：主導因素 = L_ICI_net 與 L_est 中較大者；切片 ii：L_ICI_net 與 L_est_naive 中較大者；兩者都 < 0.5 dB 記為「-」（同 map_prototype）。
 * eps_max = f_m / Δf > 0.5 的格子：CP 法的模糊（|ε| < 0.5 才有效）與整個 ε 範圍超出模型範圍 → 標記 excluded=1 並排除在比例之外。
 * 臨界點（資訊性）：對每個 (fc, Δf, v) 與 SNR，L_est_naive − L_ICI_net 在 Nr 軸（log2 線性內插）由正變負或由負變正的位置；
 *   對每個 (fc, Δf, v, Nr)，在 SNR 軸（線性內插）的位置。沒有符號變化 → 空白。
 */
const fs = require('fs'), path = require('path');
const O = require('../ofdm_ici.js');
const U = require('./_util.js');
const R = require('./reproduce_gopala_slock.js');

const VS = [0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500], FCS = [3.5, 7, 15, 28], DFS = [15, 30, 60, 120], NRS = [2, 4, 8, 16], SNRS = [10, 20, 30], C = 3e8, N = R.CFG.N, Ncp = R.CFG.Ncp, dB = x => 10 * Math.log10(x);
const DOPP = [1, -1, 0.70, 0.20], REL = [0, 0, -11, -0.7];
const HDR = 'v_kmh,fc_GHz,df_kHz,Nr,snr_db,eps_max,excluded,L_ICI_raw_db,L_est_db,L_est_se,L_est_naive_db,L_est_naive_se,n';

function cell(v, fc, df, Nr, snr, draws, seed) {
    const fm = v / 3.6 * fc * 1e9 / C, a = { opt: [], est: [], pr: [] };
    for (let t = 0; t < draws; t++) {
        const rp = O.makeRng(seed + 7919 * t), ra = O.makeRng(seed + 500000 + 7919 * t), rs = O.makeRng(seed + 1000000 + 7919 * t);
        const ang = R.pickAngles('random', ra), ch = O.makeChannel({ N, Nr, df: df * 1e3, rng: rp, paths: DOPP.map((k, i) => ({ fHz: fm * k, thetaDeg: ang[i], powerDb: REL[i] })) });
        const sn2 = O.snrToNoise(ch, snr, 1), sym = O.makeSymbol(ch, { rng: rs, sigmaX2: 1, sigmaN2: sn2, Ncp, pilotSpacing: 12 }), eh = O.epsCpEstimate(sym), Y = O.demodulate(sym, eh), s = O.system(ch, eh, 1, sn2);
        a.opt.push(dB(O.optimal(s.H, s.R, Nr, 1).sinr)); a.est.push(dB(O.sinrOfWeights(O.practicalWeights(sym, Y, { Ns: N }).G, s.H, s.R, Nr, 1))); a.pr.push(dB(O.sinrOfWeights(O.pilotResidualWeights([{ sym, Y }], {}).G, s.H, s.R, Nr, 1)));
    }
    const so = U.mean(a.opt);
    return { epsMax: fm / (df * 1e3), Lraw: 10 * Math.log10(Nr * Math.pow(10, snr / 10)) - so, Lest: so - U.mean(a.pr), LestSe: U.se(a.opt.map((x, i) => x - a.pr[i])), Lnaive: so - U.mean(a.est), LnaiveSe: U.se(a.opt.map((x, i) => x - a.est[i])) };
}
/** xs（升冪）上的 d = naive − net 由一個符號變成另一個的位置（線性內插；log 軸用 logAxis）；沒有則 null；有多個時回傳第一個 */
function crossing(xs, d, logAxis) {
    for (let i = 0; i + 1 < xs.length; i++) if ((d[i] < 0 && d[i + 1] >= 0) || (d[i] > 0 && d[i + 1] <= 0)) { const f = d[i] / (d[i] - d[i + 1]), x0 = logAxis ? Math.log2(xs[i]) : xs[i], x1 = logAxis ? Math.log2(xs[i + 1]) : xs[i + 1], x = x0 + f * (x1 - x0); return logAxis ? Math.pow(2, x) : x; }
    return null;
}
const domOf = (a, b) => Math.max(a, b) < 0.5 ? '-' : (a >= b ? 'I' : 'E');

if (require.main === module) {
    const argv = process.argv.slice(2), root = path.join(__dirname, '..', 'data');
    if (argv.includes('--merge')) {
        const files = fs.readdirSync(root).filter(f => /^map_v2\.part\d+\.csv$/.test(f)).sort(), rows = [];
        for (const f of files) rows.push(...fs.readFileSync(path.join(root, f), 'utf8').trim().split('\n').filter(l => !l.startsWith('v_kmh')).map(l => l.split(',')));
        const draws = rows[0][12], key = r => `${r[0]}|${r[1]}|${r[2]}|${r[3]}|${r[4]}`, map = new Map(rows.map(r => [key(r), r]));
        const base = {}; for (const Nr of NRS) for (const snr of SNRS) base[`${Nr}|${snr}`] = +rows.find(r => +r[0] === 0 && +r[3] === Nr && +r[4] === snr)[7];
        const out = rows.map(r => { const net = Math.max(0, +r[7] - base[`${r[3]}|${r[4]}`]); return { r, net, d1: domOf(net, +r[8]), d2: domOf(net, +r[10]) }; });
        out.sort((x, y) => (+x.r[4] - +y.r[4]) || (+x.r[3] - +y.r[3]) || (+x.r[1] - +y.r[1]) || (+x.r[2] - +y.r[2]) || (+x.r[0] - +y.r[0]));
        const hdr = ['Mini limiting-factor map v2: two slices (clean estimator / signal-in-R estimator), SNR axis added; informational, no UI',
            `schema_version 1; generated by tests/map_v2.js; seed ${R.CFG.seed}; ${draws} realisations per cell; ${out.length} cells (v x fc x delta_f x Nr x SNR); settings as data/map_prototype.csv`,
            'L_ICI_net = L_ICI_raw minus its value at v = 0 of the same (Nr, SNR), floored at 0; L_est = pilot residual (no loading, m = 1); L_est_naive = estimated with the signal in R_yy (all 1024 subcarriers)',
            'dominant_clean = larger of L_ICI_net and L_est; dominant_naive = larger of L_ICI_net and L_est_naive; I = ICI, E = estimation, - = both below 0.5 dB; excluded = 1 when eps_max = f_m / delta_f > 0.5 (outside the CP-estimator range); those cells are flagged and left out of the proportions'];
        fs.writeFileSync(path.join(root, 'map_v2.csv'), hdr.map(l => '# ' + l).join('\n') + '\nv_kmh,fc_GHz,df_kHz,Nr,snr_db,eps_max,excluded,L_ICI_net_db,L_ICI_raw_db,L_est_db,L_est_se,L_est_naive_db,L_est_naive_se,dominant_clean,dominant_naive,n\n' +
            out.map(o => [o.r[0], o.r[1], o.r[2], o.r[3], o.r[4], o.r[5], o.r[6], o.net.toFixed(3), o.r[7], o.r[8], o.r[9], o.r[10], o.r[11], o.d1, o.d2, o.r[12]].join(',')).join('\n') + '\n');
        // 比例
        const lines = [], inc = out.filter(o => o.r[6] === '0'), exc = out.length - inc.length, cnt = (arr, k) => { const c = { I: 0, E: 0, '-': 0 }; for (const o of arr) c[o[k]]++; return c; }, pc = (c, n) => `ICI ${c.I} (${U.f(100 * c.I / n, 1)} %), estimation ${c.E} (${U.f(100 * c.E / n, 1)} %), neither ${c['-']} (${U.f(100 * c['-'] / n, 1)} %)`;
        lines.push(`cells: ${out.length}; excluded (eps_max > 0.5): ${exc}; counted: ${inc.length}`);
        lines.push(`slice (i)  clean estimator (pilot residual, no loading): ${pc(cnt(inc, 'd1'), inc.length)}`);
        lines.push(`slice (ii) signal-in-R estimator (L_est_naive):          ${pc(cnt(inc, 'd2'), inc.length)}`);
        for (const snr of SNRS) for (const [k, nm] of [['d1', 'clean'], ['d2', 'naive']]) { const s = inc.filter(o => +o.r[4] === snr); lines.push(`  SNR ${snr} dB, ${nm}: ${pc(cnt(s, k), s.length)}`); }
        for (const Nr of NRS) for (const [k, nm] of [['d1', 'clean'], ['d2', 'naive']]) { const s = inc.filter(o => +o.r[3] === Nr); lines.push(`  Nr ${Nr}, ${nm}: ${pc(cnt(s, k), s.length)}`); }
        // 臨界點
        const crit = [], stats = { nr: 0, nrTot: 0, snr: 0, snrTot: 0 };
        for (const fc of FCS) for (const df of DFS) for (const v of VS) {
            if (v === 0) continue;
            const ex = (v / 3.6 * fc * 1e9 / C) / (df * 1e3) > 0.5;
            const netOf = r => Math.max(0, +r[7] - base[`${r[3]}|${r[4]}`]);
            for (const snr of SNRS) { const rs = NRS.map(Nr => map.get(`${v}|${fc}|${df}|${Nr}|${snr}`)), d = rs.map(r => +r[10] - netOf(r)), x = crossing(NRS, d, true); crit.push(['Nr', fc, df, v, snr, '', x === null ? '' : x.toFixed(2), ex ? 1 : 0]); if (!ex) { stats.nrTot++; if (x !== null) stats.nr++; } }
            for (const Nr of NRS) { const rs = SNRS.map(snr => map.get(`${v}|${fc}|${df}|${Nr}|${snr}`)), d = rs.map(r => +r[10] - netOf(r)), x = crossing(SNRS, d, false); crit.push(['SNR', fc, df, v, '', Nr, x === null ? '' : x.toFixed(2), ex ? 1 : 0]); if (!ex) { stats.snrTot++; if (x !== null) stats.snr++; } }
        }
        fs.writeFileSync(path.join(root, 'map_v2_critical.csv'), ['# Critical points where L_est_naive = L_ICI_net (linear interpolation; log2 axis for Nr; empty = no sign change inside the grid Nr 2..16 / SNR 10..30 dB); informational',
            '# axis = Nr: critical Nr for the given SNR; axis = SNR: critical SNR [dB] for the given Nr; excluded = 1: eps_max > 0.5 (left out of the counts); v = 0 is skipped (L_ICI_net = 0)'].join('\n') + '\naxis,fc_GHz,df_kHz,v_kmh,snr_db,Nr,critical_value,excluded\n' + crit.map(c => c.join(',')).join('\n') + '\n');
        lines.push(`critical points (counted cells, v > 0): a sign change of L_est_naive - L_ICI_net inside the Nr grid for ${stats.nr} of ${stats.nrTot} (fc, df, v, SNR) combinations; inside the SNR grid for ${stats.snr} of ${stats.snrTot} (fc, df, v, Nr) combinations`);
        fs.writeFileSync(path.join(root, '..', 'docs', 'diagnostics', 'map_v2_summary.txt'), lines.join('\n') + '\n'); console.log(lines.join('\n'));
    } else {
        const draws = argv.includes('--draws') ? +argv[argv.indexOf('--draws') + 1] : 200, part = argv.includes('--part') ? argv[argv.indexOf('--part') + 1].split('/').map(Number) : [0, 1], t0 = Date.now(), rows = [];
        const grid = []; for (const snr of SNRS) for (const Nr of NRS) for (const fc of FCS) for (const df of DFS) for (const v of VS) grid.push([v, fc, df, Nr, snr]);
        grid.forEach((g, gi) => {
            if (gi % part[1] !== part[0]) return;
            const [v, fc, df, Nr, snr] = g, r = cell(v, fc, df, Nr, snr, draws, R.CFG.seed);
            rows.push([v, fc, df, Nr, snr, r.epsMax.toFixed(4), r.epsMax > 0.5 ? 1 : 0, r.Lraw.toFixed(3), r.Lest.toFixed(3), r.LestSe.toFixed(3), r.Lnaive.toFixed(3), r.LnaiveSe.toFixed(3), draws].join(','));
            if (rows.length % 50 === 0) console.error(`part ${part[0]}: ${rows.length} cells (${((Date.now() - t0) / 1000).toFixed(0)} s)`);
        });
        fs.writeFileSync(path.join(root, `map_v2.part${part[0]}.csv`), HDR + '\n' + rows.join('\n') + '\n'); console.log(`part ${part[0]}/${part[1]}: ${rows.length} cells, ${((Date.now() - t0) / 1000).toFixed(0)} s`);
    }
}
module.exports = { cell, crossing, domOf, VS, FCS, DFS, NRS, SNRS };
